# Generated by Django 3.2.4 on 2021-06-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimodel', '0002_auto_20210624_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='linearmodel',
            name='Result',
            field=models.FloatField(default=70, verbose_name='Tahmini Potansiyeli'),
        ),
        migrations.AlterField(
            model_name='linearmodel',
            name='Position',
            field=models.CharField(choices=[('CAM', 'CAM'), ('CB', 'CB'), ('CDM', 'CDM'), ('CF', 'CF'), ('CF', 'CM'), ('GK', 'GK'), ('LB', 'LB'), ('LM', 'LM'), ('LW', 'LW'), ('LWB', 'LWB'), ('RB', 'RB'), ('RM', 'RM'), ('RW', 'RW'), ('RWB', 'RWB'), ('ST', 'ST')], default='CAM', max_length=50, verbose_name='Mevkisi'),
        ),
    ]
